### ISSUE TITLE
Error in recent VSCode version

### ISSUE THREAD

**Issue by ColCh** [lucax88x/CodeAceJumper#24]
`AceJump: Error: command 'extension.aceJump.input.stop' aready exists`

It seems that it comes from this line

https://github.com/lucax88x/CodeAceJumper/blob/18a785fc7ecf8a5df0926508d64e18163f805b55/src/inline-input.ts#L26

**Comment by lucax88x** [comment]
That's weird, never seen this one, did you try to reinstall this?

**Comment by ColCh** [comment]
Yup, same result

**Comment by lucax88x** [comment]
Hm, can you print me out your list of exstensions? Maybe someone that copied my code? Anyway I'm gonna add some check in that line of code

**Comment by ColCh** [comment]
Yeah, sure

That's pretty long list

here it is:

<details>
<pre>
MariusAlchimavicius.json-to-ts
TeddyDD.fish
aaron-bond.better-comments
aaronduino.paste-fixer
abierbaum.vscode-file-peek
abusaidm.html-snippets
adammaras.overtype
airstep.yandex-translate
albymor.increment-selection
alefragnani.Bookmarks
alefragnani.project-manager
alexdima.vscode-lcov
aliariff.auto-add-brackets
alqiu.ts-loader-problem-matcher
anseki.vscode-color
anweber.statusbar-commands
bierner.emojisense
cancerberosgx.vscode-typescript-refactors
capaj.vscode-exports-autocomplete
ccimage.jsonviewer
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
christianoetterli.refactorix
closedcontour.very-smart-select
cmstead.jsrefactor
CoenraadS.bracket-pair-colorizer
CoenraadS.disableligatures
colch.quick-open-prefill-selection
crazywolf.smali
dakara.transformer
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
dbankier.vscode-quick-select
deerawan.vscode-faker
devine-davies.make-hidden
donjayamanne.githistory
DotJoshJohnson.xml
dsznajder.es7-react-js-snippets
eamodio.gitlens
eamodio.toggle-excluded-files
earshinov.sort-lines-by-selection
ecmel.vscode-html-css
EditorConfig.EditorConfig
eg2.tslint
eg2.vscode-npm-script
emeraldwalk.RunOnSave
emmanuelbeziat.vscode-great-icons
esbenp.prettier-vscode
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
formulahendry.code-runner
foxundermoon.shell-format
gamunu.vscode-yarn
gazugafan.vscode-indent-on-paste
geddski.macros
gegeke.node-modules-navigation
gharveymn.nightswitch-lite
Gruntfuggly.triggertaskonsave
heaths.vscode-guid
helixquar.randomeverything
HookyQR.beautify
HookyQR.CreateModule
hoovercj.vscode-dimmer
hoovercj.vscode-power-mode
in4margaret.compareit
jakob101.RelativePath
jasonlhy.hungry-delete
jasonnutter.search-node-modules
jaydenlin.google-complete-me
jbhannah.autopairs-code
jebbs.markdown-extended
jedmao.tabsanity
joelday.docthis
jrebocho.vscode-random
jrieken.backspace-plusplus
kisstkondoros.typelens
konstantin.wrapSelection
krizzdewizz.tag-rename
krizzdewizz.vscode-icon-rotation
kumar-harsh.graphql-for-vscode
lehni.vscode-titlebar-less-macos
letrieu.expand-region
lfurzewaddock.vscode-opn
lihui.vs-color-picker
lucax88x.codeacejumper
lunarlimbo.banner-comments-plus
lunaryorn.fish-ide
mhmadhamster.postcss-language
mikerhyssmith.ts-barrelr
mikestead.dotenv
mitchdenny.ecdc
mohsen1.prettify-json
moppitz.vscode-extension-auto-import
mrmlnc.vscode-attrs-sorter
mrmlnc.vscode-csscomb
ms-vscode.cpptools
msjsdiag.debugger-for-chrome
naumovs.color-highlight
nemesv.copy-file-name
nmsmith89.incrementor
oderwat.indent-rainbow
oliversturm.fix-json
OnlyLys.leaper
Orta.vscode-jest
ow.vscode-subword-navigation
patrys.vscode-code-outline
PeterJausovec.vscode-docker
pflannery.vscode-versionlens
pnp.polacode
pranaygp.vscode-css-peek
quicktype.quicktype
rhystyers.csstojs
riazxrazor.html-to-jsx
rusnasonov.vscode-typograf
ryu1kn.partial-diff
Shan.code-settings-sync
shardulm94.trailing-spaces
skyapps.fish-vscode
sleistner.vscode-fileutils
slevesque.vscode-zipexplorer
speks.flowmaker
spikespaz.vscode-smoothtype
spywhere.mark-jump
spywhere.whiteviz
steve8708.Align
stkb.rewrap
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-russian
swashata.beautiful-ui
sysoev.language-stylus
teabyii.ayu
TomasHubelbauer.markdown-jira-links
TomiTurtiainen.js-complexity-analysis
Tyriar.sort-lines
vincaslt.highlight-matching-tag
VisualStudioExptTeam.vscodeintellicode
vittorioromeo.expand-selection-to-scope
vmsynkov.colonize
waderyan.babelrc
wayou.vscode-todo-highlight
wengerk.highlight-bad-chars
wix.glean
wix.vscode-import-cost
wmaurer.change-case
yatki.vscode-surround
yhpnoraa.beauty
yzhang.dictionary-completion
yzhang.markdown-all-in-one
zengxingxin.sort-js-object-keys
ziyasal.vscode-open-in-github
</pre>
</details>

quick search for command in extension directory. same for `input.stop`

```
~/.v/extensions $ rg 'aceJump.input.stop'
lucax88x.codeacejumper-1.1.8/package.json
46:				"command": "extension.aceJump.input.stop",

lucax88x.codeacejumper-1.1.8/out/src/inline-input.js
63:        this.registerTextEditorCommand('extension.aceJump.input.stop', this.cancel);
```

**Comment by ColCh** [comment]
Other error is `AceJump: Error: command 'type' aready exists`

registers here

https://github.com/lucax88x/CodeAceJumper/blob/18a785fc7ecf8a5df0926508d64e18163f805b55/src/inline-input.ts#L47


debugged a bit

stacktrace

<details>
<summary>logs</summary>
<pre>
Error: command 'type' already exists
	at e.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:451:595)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:603:111)
	at InlineInput.__dirname.constructor.registerCommand (/Users/colch/.vscode/extensions/lucax88x.codeacejumper-1.1.8/out/src/inline-input.js:40:53)
	at InlineInput.__dirname.constructor.show (/Users/colch/.vscode/extensions/lucax88x.codeacejumper-1.1.8/out/src/inline-input.js:29:18)
	at __dirname.constructor.jump.Promise (/Users/colch/.vscode/extensions/lucax88x.codeacejumper-1.1.8/out/src/acejump.js:83:26)
	at new Promise (<anonymous>)
	at __dirname.constructor.jump.Promise (/Users/colch/.vscode/extensions/lucax88x.codeacejumper-1.1.8/out/src/acejump.js:81:33)
	at new Promise (<anonymous>)
	at AceJump.__dirname.constructor.jump (/Users/colch/.vscode/extensions/lucax88x.codeacejumper-1.1.8/out/src/acejump.js:74:20)
	at __dirname.constructor.configure.disposables.push.vscode.commands.registerCommand (/Users/colch/.vscode/extensions/lucax88x.codeacejumper-1.1.8/out/src/acejump.js:22:26)
	at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:452:706)
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:453:212)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:640:888)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:640:554)
	at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:639:126)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:638:59)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:926
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:138
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:496)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:213)
	at Socket.n._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
</pre>
</details>


Gotcha!
<details><summary>Got it</summary><img src="https://user-images.githubusercontent.com/599439/47264236-5adbfd00-d51b-11e8-9cd7-a9e1806747b8.png"></details>

Uninstalled it and CodeAceJumper now works 👍 

It seems that command `type` should be unique. May be, prefixed with this extension name.

**Comment by ColCh** [comment]
Related to https://github.com/Microsoft/vscode/issues/13441

**Comment by ColCh** [comment]
Actually, this issue comes from `Overtype` extension

I've created issue for that extension https://github.com/AdamMaras/vscode-overtype/issues/12

Nothing to do with CodeAceJumper in this case, so feel free to close this issue if you want to

**Comment by lucax88x** [comment]
Yeah, the problem regarding "type" command is still unsolved since ages, extensions like the emacs, vim emulator and this one cannot coexist because of that.

More than registering this command only when requesting I cannot do, unfortunately :(

What about the "input.stop" problem? you still have it?

**Comment by ColCh** [comment]
> More than registering this command only when requesting I cannot do, unfortunately :(


yup and it seems that it should be fixed in `overtype` extension

> What about the "input.stop" problem? you still have it?

no, my friend, it's gone with `overtype` uninstall
